# Event bus for views
VIEW_EVENT_BUS_NAME = 'VIEW_EVENT_BUS'


FIGURE_WAS_CHOSE = 'FIGURE_WAS_CHOSE'
OPEN_FIGURE_CHOOSE_POPUP = 'OPEN_FIGURE_CHOOSE_POPUP'
CLOSE_FIGURE_CHOOSE_POPUP = 'CLOSE_FIGURE_CHOOSE_POPUP'
